### ISSUE TITLE
Missing OPTiMaDe response fields

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/providers#13] opened 2020-01-22 23:52 UTC
Even with the few tweaks added today, https://optimade.org/providers still will not validate as an optimade implentatio as the static data we are hosting is missing the standard optimade response fields (basically just`meta`). How much do we care about this?

**Comment by rartino** [comment] 2020-01-23 00:36
Just evaluating the response as a regular OPTiMaDe response, section 4.2 of the present specification says: "Every response SHOULD contain the following fields, and MUST contain at least one" and then lists `meta` and `data`. Hence, it is only a SHOULD level requirement that `meta` is included, not a MUST. Can the validator handle the difference between SHOULD and MUST? If it says the response is completely invalid, then that is a bug with the schema.

Furthermore, there is PR #236 that suggest adding that specifically for index meta-databases served via static files, this SHOULD requirement is downgraded to a say it is RECOMMENDED not to include `meta` in the response.

**Comment by ml-evs** [comment] 2020-01-23 10:02
Interesting, thanks for the link to the PR, I agree with the downgrade. Seems like we are being too strict in the python models.

**Comment by CasperWA** [comment] 2020-01-23 10:17
We should have taken this into account in the models with a validator for the top-level responses, but if it's not held, it's definitely a bug.

**Comment by ml-evs** [comment] 2020-01-23 10:22
> We should have taken this into account in the models with a validator for the top-level responses, but if it's not held, it's definitely a bug.

Seems like there's a bug with the root_validator of the base `Response` class, it's not receiving the "data" (and all other fields are None) so its failing. If I can't fix this in the next 10 mins myself I'll raise an issue.

**Comment by CasperWA** [comment] 2020-01-24 10:47
Closing this, since the issue is not with the response from this repo's OPTiMaDe implementation, but with the validator - something that is expected to be fixed with Materials-Consortia/optimade-python-tools#145.

**Closed by CasperWA** 2020-01-24 10:47 UTC
